"""add budget columns and monthly goals table

Revision ID: 5763d5f6c813
Revises: c9c2086937d8
Create Date: 2026-04-12 11:43:38.383130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5763d5f6c813'
down_revision: Union[str, None] = 'c9c2086937d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_budget', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('is_budget_fixed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_budget_fixed')
    op.drop_column('users', 'default_budget')
    # ### end Alembic commands ###
