"""Initial schema

Revision ID: c9c2086937d8
Revises: 
Create Date: 2026-04-11 21:35:58.360823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9c2086937d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=True),
    sa.Column('merchant_id', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('taxes', sa.Float(), nullable=True),
    sa.Column('qr_data', sa.Text(), nullable=True),
    sa.Column('access_key', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_access_key'), 'receipts', ['access_key'], unique=True)
    op.create_index(op.f('ix_receipts_id'), 'receipts', ['id'], unique=False)
    op.create_index(op.f('ix_receipts_merchant_id'), 'receipts', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_receipts_store_name'), 'receipts', ['store_name'], unique=False)
    op.create_table('receipt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('product_code', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_items_id'), 'receipt_items', ['id'], unique=False)
    op.create_index(op.f('ix_receipt_items_product_name'), 'receipt_items', ['product_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_items_product_name'), table_name='receipt_items')
    op.drop_index(op.f('ix_receipt_items_id'), table_name='receipt_items')
    op.drop_table('receipt_items')
    op.drop_index(op.f('ix_receipts_store_name'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_merchant_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_access_key'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
